version: "3.7"
services:
  database:
    container_name: "creditcalculator-database"
    build: ./database/
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    init: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    container_name: "creditcalculator-backend"
    build:
      context: ./backend
      args:
        - APPLICATION_NAME=backend
        - APPLICATION_VERSION=0.0.1
        - APPLICATION_HOST=database
        - APPLICATION_DB=creditcalculatordb
        - APPLICATION_USER=creditcalculator
        - APPLICATION_PASSWORD=yZnaaX4ZeIeVdahDedQQ
    depends_on:
      - database
    ports:
      - "8080:8080"

  frontend:
    container_name: "creditcalculator-frontend"
    build:
      context: ./frontend/
      args:
        - APPLICATION_NAME=frontend
        - APPLICATION_VERSION=0.0.1
    depends_on:
      - backend
    ports:
      - "8081:8080"
volumes:
  db-data:
